Python3 fix when blocking on contented lock
The default of "None" triggers:
TypeError: unorderable types: NoneType() > int()

Introducing failing test case + fix; mocked API response may be wonky
but it demonstrates issue.